# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: nevaeh5379.HaejeokRisuai
PackageVersion: 0.0.7538
PackageLocale: ko-KR
Publisher: nevaeh5379
PublisherUrl: https://github.com/nevaeh5379/HaejeokRisuai
PublisherSupportUrl: https://github.com/nevaeh5379/HaejeokRisuai/issues
PrivacyUrl: https://github.com/nevaeh5379/HaejeokRisuai
Author: nevaeh5379
PackageName: HaejeokRisuai
PackageUrl: https://github.com/nevaeh5379/HaejeokRisuai
License: GPL-3.0 license
LicenseUrl: https://raw.githubusercontent.com/nevaeh5379/HaejeokRisuai/refs/heads/main/LICENSE
ShortDescription: HaejeokRisuai is a fork of the Risuai repository.
Description: HaejeokRisuai is a fork of the Risuai repository.
Tags:
- risuai
ManifestType: defaultLocale
ManifestVersion: 1.12.0
