# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.12.0.schema.json

PackageIdentifier: nevaeh5379.HaejeokRisuai
PackageVersion: 0.0.7538
DefaultLocale: ko-KR
ManifestType: version
ManifestVersion: 1.12.0
